#!/bin/bash
# Create (or update) a DRAFT GitHub release with all firmware .uf2 files.
#
# The release is created as a draft: the git tag and the auto-generated
# "Source code (zip/tar.gz)" archives appear only when you publish it
# (gh release edit vX.Y.Z --draft=false, or the web UI). Until then the
# draft is invisible to users and can be freely edited or deleted.
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# --- Pico SDK tools bootstrap ---
# The VS Code Pico extension injects cmake/toolchain into its own terminals;
# plain shells (cron, CI, Claude background tasks) don't have them on PATH.
if ! command -v cmake >/dev/null 2>&1; then
    CMAKE_BIN=$(ls -d "$HOME/.pico-sdk/cmake"/*/bin 2>/dev/null | sort -V | tail -1)
    [ -n "$CMAKE_BIN" ] && export PATH="$CMAKE_BIN:$PATH"
fi
if [ -z "$PICO_TOOLCHAIN_PATH" ]; then
    TC_VER=$(grep -oP 'set\(toolchainVersion \K[^)]+' CMakeLists.txt)
    TC_DIR="$HOME/.pico-sdk/toolchain/$TC_VER"
    if [ -d "$TC_DIR" ]; then
        export PICO_TOOLCHAIN_PATH="$TC_DIR"
        export PATH="$TC_DIR/bin:$PATH"
    fi
fi

REPO="drewpo28/pico-spec"
SKIP_BUILD=false
NOTES_FILE=""
NEW_VERSION=""

usage() {
    cat <<EOF
Usage: $0 [NEW_VERSION] [--skip-build] [--notes FILE]

  NEW_VERSION   Optional, e.g. 1.2.27. Bumps PORT_VERSION in CMakeLists.txt,
                commits and pushes that commit (the draft must target a commit
                that exists on GitHub). Without it the current PORT_VERSION
                from CMakeLists.txt is used.
  --skip-build  Reuse firmware/*.uf2 from a previous build_all.sh run.
  --notes FILE  Release notes file. Default: RELEASE_NOTES.md if present,
                otherwise GitHub auto-generated notes.

Publish later with:  gh release edit vX.Y.Z --draft=false
EOF
    exit 0
}

while [ $# -gt 0 ]; do
    case "$1" in
        --skip-build) SKIP_BUILD=true; shift ;;
        --notes)      NOTES_FILE="$2"; shift 2 ;;
        -h|--help)    usage ;;
        [0-9]*.[0-9]*.[0-9]*) NEW_VERSION="$1"; shift ;;
        *) echo "Unknown argument: $1 (see --help)"; exit 1 ;;
    esac
done

CUR_VERSION=$(grep -oP 'set \(PORT_VERSION "\K[0-9.]+' CMakeLists.txt)
if [ -z "$CUR_VERSION" ]; then
    echo "Error: could not parse PORT_VERSION from CMakeLists.txt"
    exit 1
fi

# --- Optional version bump (commit + push, so the draft can target it) ---
if [ -n "$NEW_VERSION" ] && [ "$NEW_VERSION" != "$CUR_VERSION" ]; then
    if ! git diff --quiet || ! git diff --cached --quiet; then
        echo "Error: working tree has uncommitted changes; commit or stash them"
        echo "       before bumping the version (the bump is its own commit)."
        exit 1
    fi
    echo "Bumping PORT_VERSION: $CUR_VERSION -> $NEW_VERSION"
    sed -i "s/set (PORT_VERSION \"$CUR_VERSION\")/set (PORT_VERSION \"$NEW_VERSION\")/" CMakeLists.txt
    git add CMakeLists.txt
    git commit -m "Bump version to $NEW_VERSION"
    git push origin "$(git branch --show-current)"
    VER="$NEW_VERSION"
else
    VER="$CUR_VERSION"
fi
TAG="v$VER"

# --- The draft targets HEAD, which must exist on GitHub ---
git fetch origin --quiet
HEAD_SHA=$(git rev-parse HEAD)
if ! git merge-base --is-ancestor "$HEAD_SHA" "origin/$(git branch --show-current)" 2>/dev/null; then
    echo "Error: HEAD ($HEAD_SHA) is not pushed to origin."
    echo "       Push your branch first: git push origin $(git branch --show-current)"
    exit 1
fi

# --- Build ---
if $SKIP_BUILD; then
    echo "Skipping build (reusing firmware/)"
else
    ./build_all.sh
fi

# firmware/ must hold exactly this version's uf2s (build_all.sh cleans it,
# but --skip-build after a version bump would leave stale files)
FILES=(firmware/*-"$VER".uf2)
if [ ! -f "${FILES[0]}" ]; then
    echo "Error: no firmware/*-$VER.uf2 files found — run without --skip-build"
    exit 1
fi
STALE=$(ls firmware/*.uf2 | grep -v -- "-$VER.uf2" || true)
if [ -n "$STALE" ]; then
    echo "Error: firmware/ contains files of another version:"
    echo "$STALE"
    exit 1
fi
echo ""
echo "Firmware files (${#FILES[@]}):"
printf '  %s\n' "${FILES[@]##*/}"
echo ""

# --- Release notes ---
NOTES_ARGS=(--generate-notes)
if [ -z "$NOTES_FILE" ] && [ -f RELEASE_NOTES.md ]; then
    NOTES_FILE="RELEASE_NOTES.md"
fi
if [ -n "$NOTES_FILE" ]; then
    if [ ! -f "$NOTES_FILE" ]; then
        echo "Error: notes file not found: $NOTES_FILE"
        exit 1
    fi
    NOTES_ARGS=(--notes-file "$NOTES_FILE")
    echo "Release notes: $NOTES_FILE"
else
    echo "Release notes: auto-generated by GitHub"
fi

# --- Create draft, or update assets of an existing release ---
if gh release view "$TAG" -R "$REPO" >/dev/null 2>&1; then
    echo "Release $TAG already exists — updating assets (--clobber)"
    gh release upload "$TAG" -R "$REPO" --clobber "${FILES[@]}"
    if [ -n "$NOTES_FILE" ]; then
        gh release edit "$TAG" -R "$REPO" --notes-file "$NOTES_FILE"
    fi
else
    gh release create "$TAG" -R "$REPO" \
        --draft \
        --title "$VER" \
        --target "$HEAD_SHA" \
        "${NOTES_ARGS[@]}" \
        "${FILES[@]}"
fi

echo ""
gh release view "$TAG" -R "$REPO" --json url,isDraft \
    --template 'Release: {{.url}}  (draft: {{.isDraft}})
'
echo "Publish with:  gh release edit $TAG -R $REPO --draft=false"
